async function askQuestion() {
  const question = document.getElementById('questionInput').value.trim();
  const loading = document.getElementById('loading');
  const result = document.getElementById('result');
  const error = document.getElementById('error');
  const badge = document.getElementById('badge');
  const answer = document.getElementById('answer');

  // Reset
  result.classList.add('hidden');
  error.classList.add('hidden');

  if (!question) {
    error.textContent = 'Please enter a question.';
    error.classList.remove('hidden');
    return;
  }

  loading.classList.remove('hidden');

  try {
    const response = await fetch('http://localhost:5000/ask', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question })
    });

    const data = await response.json();
    loading.classList.add('hidden');

    if (!response.ok) {
      error.textContent = 'Error: ' + (data.details?.join(', ') || data.error);
      error.classList.remove('hidden');
      return;
    }

    if (data.source === 'cache') {
      badge.textContent = '✓ Cached Answer';
      badge.className = 'badge-blockchain';
    } else {
      badge.textContent = '🤖 Generated by AI (now cached)';
      badge.className = 'badge-ai';
    }

    answer.textContent = data.answer;
    result.classList.remove('hidden');

  } catch (err) {
    loading.classList.add('hidden');
    error.textContent = 'Could not connect to server. Is Flask running?';
    error.classList.remove('hidden');
  }
}

// Allow pressing Enter to submit
document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('questionInput')
    .addEventListener('keypress', (e) => {
      if (e.key === 'Enter') askQuestion();
    });
});